apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: db-container2
  name: db-container2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-container2
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/kuber-default: "true"
        io.kompose.service: db-container2
    spec:
      containers:
          image: crkot3/checha20:db-container2
          name: db-container2
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
      restartPolicy: Always
