apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: task-manager
  name: task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: task-manager
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/kuber-default: "true"
        io.kompose.service: task-manager
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: r2dbc:pool:mysql://db-container2:3306/tmpdb
            - name: SPRING_DATASOURCE_USERNAME
              value: finley
          image: crkot3/checha20:tgbot
          name: task-manager
          ports:
            - containerPort: 8069
              hostPort: 8069
              protocol: TCP
      restartPolicy: Always
